name: Run Repo Unit Tests

on:
  push:
    branches: [main]
  pull_reuqest:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm test
  
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
      - run: npm ci
      - run: npm build
  
